Home Screen
RenanPaixao/Remake pull request #12
Opened 2023-07-27 06:35 UTC by hipera09

#4 
Esse PR diz respeito a versão inicial da home-page, ela em si ainda precisa de algumas poucas alterações/finalizações mas é uma implementação inicial.

- Nesse PR eu criei os elementos da pagina como: os botões das categorias, e os links para o FAQ( quando existir ) e o Link direto para lista de locais próximos junto com o titulo da pagina.
- Caso precise de mais alguma adição ou alteração posso fazer no decorrer do PR ou em outro para que esse não fique muito grande.

### HomePage

![image](https://github.com/RenanPaixao/Remake/assets/71048167/0bf5b9ff-3e02-4dbc-bcc0-b58f18666837)

2023-07-27 12:02 UTC, RenanPaixao requested changes

2023-07-27 12:02 UTC, RenanPaixao commented on app/src/screens/Home.tsx
> +import { supabase } from '../initSupabase';
Não vejo onde o supabase está sendo usado

2023-07-27 12:02 UTC, RenanPaixao commented on app/src/screens/Home.tsx
> +// Estilos
Pode remover esses comentários? Vou comentar nos outros. Teu código tá claro o suficiente

Também, lembra de comentar em inglês, beleza?

2023-07-27 12:02 UTC, RenanPaixao commented on app/src/screens/Home.tsx
> +// Componente botão link
Comentário

2023-07-27 12:02 UTC, RenanPaixao commented on app/src/screens/Home.tsx
> +);
N acho que agt deveria ter criado esse componente aqui. Usar ele diretamente no código seria mais coerente pq ele n tem nenhuma lógica que parece boa pra componentizar

2023-07-27 12:02 UTC, RenanPaixao commented on app/src/screens/Home.tsx
> +            {/* Botões */}
comentário

2023-07-27 14:58 UTC, hipera09 commented on app/src/screens/Home.tsx
> +);
Foi só pra reutilizar o style no outro aparecimento dele em baixo, mas transformo em uma view com o style proprio? acha melhor?

2023-07-27 14:59 UTC, hipera09 commented on app/src/screens/Home.tsx
> +import { supabase } from '../initSupabase';
Eu não tinha visto esse import ele já tava no codigo, vou remover!

2023-07-28 00:43 UTC, RenanPaixao approved these changes

2023-07-28 00:43 UTC, RenanPaixao commented on app/src/screens/Home.tsx
> +);
De boa, vou aprovar

2023-07-28 00:44 UTC, merged