Feat/faq screen
RenanPaixao/Remake pull request #20
Opened 2023-08-03 20:17 UTC by hipera09

#14 
Esse PR diz respeito a versão inicial da faq-page, ela em si ainda precisa de alguns detalhes e uma refatoração/organização da estrutura do código, porém estou abrindo esse PR com a versão inicial para agregar na apresentação do front-end.

- Nesse PR eu criei os elementos da pagina como: o input para enviar pergunta para o chatGPT, a sessão de resposta do post junto com a visualização dessa resposta e por fim a criação do componente sanfona com algumas perguntas base.
- Criação da rota FAQ da tela inicial
- Caso precise de mais alguma adição ou alteração posso fazer no decorrer do PR, por isso peço que quando fizer o merge após possiveis modificações não encerre a branch :)

### FaqPage

![faqpage](https://github.com/RenanPaixao/Remake/assets/71048167/2ed77450-a9f3-4994-88a3-b479fd577494)

2023-08-03 21:35 UTC, albertojcvs requested changes

2023-08-03 21:35 UTC, albertojcvs commented on app/src/screens/Faq/Faq.tsx
> +const supabase = createClient('https://izgjtgdyvjzrsyxtabfx.supabase.co/functions/v1/material-type', 'public-anon-key')
Mano, só uma coisa, a gente tá utilizando meio que um padrão, para utilizar esses serviços externos do supabase, do brasilApi ou de outro lugar, a gente tá criando um arquivo de service que nem [ esse aqui ](https://github.com/RenanPaixao/Remake/blob/main/app/src/services/companies/companiesService.ts)

tambem tá sendo utilizado esse [cara daqui](https://github.com/RenanPaixao/Remake/blob/main/app/src/initSupabase.ts) para criar o client do supabase

2023-08-03 22:10 UTC, RenanPaixao requested changes

2023-08-03 22:10 UTC, RenanPaixao commented on app/src/screens/Faq/Accordion.tsx
> +            {expanded && <Text style={styles.content}>{content}</Text>}
um ícone seria melhor que a string com o sinal de menos ('-') e sinal de mais ('+').

Exemplo do sinal de menos
- https://icons.expo.fyi/Index/Entypo/minus
- https://icons.expo.fyi/Index/AntDesign/minuscircle

Ainda, o sinal está indo pra baixo do texto, quando deveria ficar ao lado. Pode consertar isso?

![image](https://github.com/RenanPaixao/Remake/assets/57810270/d2b8b33e-cde9-4194-a8eb-8ab15d7f52f6)

Pode ser legal aumentar o tamanho do ícone

2023-08-03 22:10 UTC, RenanPaixao commented on app/src/screens/Faq/Faq.tsx
> +});
Nós temos um sistema de serviços pra remover a lógica de requests de dentro dos components.

Pode dar uma olhada nas pasta `services` e seguir algum exemplo de service já criado?

2023-08-03 22:10 UTC, RenanPaixao commented on app/src/screens/Faq/Faq.tsx
> +    console.log('Texto inserido:', searchText);
Pode remover esse console.log?

2023-08-03 22:10 UTC, RenanPaixao commented on app/src/screens/Faq/Faq.tsx
> +  // Função para atualizar o estado do input
Escreve código inteiro em inglês, inclusive comentários

2023-08-03 22:10 UTC, RenanPaixao commented on app/src/screens/Faq/Faq.tsx
> +    console.log('Resposta:', data);
Remove esse e todos os consoles desnecessários, pfv

2023-08-03 22:10 UTC, RenanPaixao commented on app/src/screens/Faq/Faq.tsx
> +  }, [response]);
console

2023-08-03 22:10 UTC, RenanPaixao commented on app/src/screens/Faq/Faq.tsx
> +  };
pra essas funções bem simples, fica mais interessante usar direto componente.

ex.:
```js
onChangeText={(text) => setSearchText(text)}
```

2023-08-03 22:10 UTC, RenanPaixao commented on app/src/screens/Faq/Faq.tsx
> +  )}
Pode deixar essa lógica mais simples? Tá bem confuso com os if ternários aninhados.

Usar ternários assim é considerado uma má prática, pela dificuldade de leitura

2023-08-04 16:57 UTC, albertojcvs approved these changes

2023-08-04 21:51 UTC, RenanPaixao approved these changes

2023-08-04 21:51 UTC, RenanPaixao commented on app/src/screens/Faq/Faq.tsx
> +  useEffect(() => { }, [response]);
Não precisa adicionar coisas que talvez iremos usar no futuro. Se formos realmente usar, a gt vai criar na hora, saca?

2023-08-04 21:51 UTC, RenanPaixao commented on app/src/services/supabase/materialTypeService.ts
> +  };
```suggestion
    return data
  };
```

2023-08-04 21:51 UTC, RenanPaixao commented on app/src/screens/Home.tsx
> +        <Section style={{ marginTop:-30}}>
Cuidado com margens negativas bele? É algo que raramente deveríamos usar

2023-08-04 21:56 UTC, merged